package com.example.colorospredictiveback;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.widget.LinearLayout;
import android.widget.TextView;

/**
 * Real ColorOS Shell test path.
 *
 * This Activity intentionally installs no OnBackInvoked/OnBackAnimation callback and no custom
 * activity/window transition. On ColorOS, that leaves the predictive transition in SystemUI/Shell,
 * where the OEM build can route it through AdaptiveSmoothShellAnimManager and
 * ShellContinuousTransitionController. Nothing in this Activity recreates that animation.
 */
public final class SystemBackActivity extends Activity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        getWindow().setStatusBarColor(Color.rgb(226, 236, 255));
        getWindow().setNavigationBarColor(Color.rgb(226, 236, 255));
        getWindow().getDecorView().setSystemUiVisibility(
                View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR | View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);

        LinearLayout root = new LinearLayout(this);
        root.setOrientation(LinearLayout.VERTICAL);
        root.setGravity(Gravity.CENTER);
        root.setPadding(dp(28), dp(28), dp(28), dp(28));
        root.setBackgroundColor(Color.rgb(226, 236, 255));

        TextView badge = label("REAL COLOROS SHELL PATH", 13, true);
        badge.setTextColor(Color.rgb(51, 88, 169));
        root.addView(badge, wrap());

        TextView title = label("Predictive Back → OEM continuous handoff", 25, true);
        title.setTextColor(Color.rgb(24, 40, 72));
        title.setGravity(Gravity.CENTER);
        LinearLayout.LayoutParams titleLp = wrap();
        titleLp.topMargin = dp(14);
        root.addView(title, titleLp);

        TextView body = label(
                "Edge-swipe back slowly, hold halfway, then commit.\n\n"
                        + "This page does NOT receive BackEvent.progress. It does NOT run a View/shared-element animator. The system owns the task/window leash. On the ColorOS 17 build we reversed, the relevant OEM chain is:\n\n"
                        + "BackAnimationController\n"
                        + "→ BackTransitionHandler\n"
                        + "→ AdaptiveSmoothShellAnimManager\n"
                        + "→ ShellContinuousTransitionController\n"
                        + "→ SpringSlideAnimationController / default transition continuation\n\n"
                        + "If the OEM predictive-continuous gate is enabled for this package/build, the handoff you see here is generated by ColorOS SystemUI itself.",
                16, false);
        body.setTextColor(Color.rgb(50, 63, 91));
        body.setGravity(Gravity.CENTER);
        LinearLayout.LayoutParams bodyLp = wrap();
        bodyLp.topMargin = dp(20);
        root.addView(body, bodyLp);

        setContentView(root);
    }

    private TextView label(String value, int sp, boolean bold) {
        TextView text = new TextView(this);
        text.setText(value);
        text.setTextSize(sp);
        text.setLineSpacing(0f, 1.18f);
        if (bold) text.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);
        return text;
    }

    private LinearLayout.LayoutParams wrap() {
        return new LinearLayout.LayoutParams(
                LinearLayout.LayoutParams.MATCH_PARENT,
                LinearLayout.LayoutParams.WRAP_CONTENT);
    }

    private int dp(int value) {
        return Math.round(value * getResources().getDisplayMetrics().density);
    }
}
