<script setup>
import { computed, ref } from 'vue'; import { ApiError, api, session } from './api';
function slot(dayOffset,hour){const d=new Date(Date.now()+dayOffset*86400000);d.setHours(hour,0,0,0);const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`}
const username=ref(''),password=ref(''),user=ref(null),rows=ref([]),labId=ref(null),title=ref(''),purpose=ref(''),startTime=ref(slot(1,14)),endTime=ref(slot(1,16)),error=ref(''),notice=ref(''),busy=ref(false);const count=computed(()=>rows.value.length);const available=computed(()=>rows.value.filter(x=>x.enabled!==false&&x.status!=='DISABLED'));
function logout(m=''){session.token='';user.value=null;rows.value=[];labId.value=null;if(m)error.value=m}function fail(e){if(e instanceof ApiError&&e.status===401)return logout('会话已失效，请重新登录');error.value=e?.message||'操作失败，请重试'}
async function load(){try{rows.value=await api('/api/labs');if(!available.value.some(x=>x.id===labId.value))labId.value=available.value[0]?.id??null}catch(e){fail(e)}}
async function login(){if(!username.value.trim()||!password.value)return;busy.value=true;error.value='';try{const r=await api('/api/auth/login',{method:'POST',body:JSON.stringify({username:username.value.trim(),password:password.value})});session.token=r.token;user.value=r.user;password.value='';await load()}catch(e){fail(e)}finally{busy.value=false}}
async function reserve(){if(!labId.value||!title.value.trim()||!purpose.value.trim()||!startTime.value||!endTime.value){return}if(new Date(endTime.value)<=new Date(startTime.value)){error.value='结束时间必须晚于开始时间';return}busy.value=true;error.value='';notice.value='';try{const normalize=v=>v.length===16?v+':00':v;await api('/api/reservations',{method:'POST',body:JSON.stringify({labId:labId.value,title:title.value.trim(),purpose:purpose.value.trim(),startTime:normalize(startTime.value),endTime:normalize(endTime.value)})});notice.value='实验室预约已提交。';title.value='';purpose.value=''}catch(e){fail(e)}finally{busy.value=false}}
</script>
<template><div class="app-shell"><div class="gridline">NODE 09 / RESERVATION MATRIX / ONLINE</div><main class="main"><header class="top"><div><p class="eyebrow">实验资源预约控制台</p><h1>LAB GRID</h1></div><div v-if="user" class="account"><span>{{user.displayName}} · {{user.role}}</span><button class="ghost" @click="logout()">退出</button></div></header><section v-if="!user" class="login-card"><div><small>SECURE ACCESS</small><h2>进入 LAB GRID</h2><p>登录后查看实验室资源并提交有时间边界的预约。</p></div><form @submit.prevent="login"><label>用户名<input v-model.trim="username" autocomplete="username" maxlength="32" required></label><label>密码<input v-model="password" type="password" autocomplete="current-password" minlength="12" maxlength="128" required></label><button :disabled="busy">{{busy?'登录中…':'登录'}}</button></form></section><template v-else><section class="hero"><div><span class="kicker">实验室</span><strong>{{count}}</strong><p>当前资源</p></div><div class="hero-copy"><h2>校园实验室预约管理系统</h2><p>预约对象来自实时实验室列表；服务端以事务锁和时间重叠检测阻止并发冲突。</p></div></section><section class="action-panel"><div><span class="kicker">RESERVATION</span><h3>新建预约</h3><p>选择实验室，填写用途并设置明确的起止时间。</p></div><form @submit.prevent="reserve"><label>实验室<select v-model.number="labId" required><option disabled :value="null">请选择实验室</option><option v-for="l in available" :key="l.id" :value="l.id">{{l.name||l.code||('实验室 #'+l.id)}} · {{l.building||''}}</option></select></label><label>预约标题<input v-model.trim="title" maxlength="255" required></label><label>用途<textarea v-model.trim="purpose" maxlength="2000" rows="3" required></textarea></label><div class="two"><label>开始时间<input v-model="startTime" type="datetime-local" required></label><label>结束时间<input v-model="endTime" type="datetime-local" required></label></div><button :disabled="busy||!labId">提交预约</button></form></section><p v-if="notice" class="notice" role="status">{{notice}}</p><p v-if="error" class="error" role="alert">{{error}}</p><section class="panel"><div class="panel-head"><h3>实验室</h3><button class="ghost" :disabled="busy" @click="load">刷新</button></div><div class="cards"><article v-for="row in rows" :key="row.id" class="data-card"><span class="id">#{{row.id}}</span><h4>{{row.name||row.code||('实验室 '+row.id)}}</h4><p>{{row.building||row.description||'位置待补充'}}</p><small>{{row.status||'AVAILABLE'}}</small></article><div v-if="!rows.length" class="empty">暂无实验室</div></div></section></template></main></div></template>
<style scoped>.action-panel{display:grid;grid-template-columns:minmax(220px,.6fr) minmax(340px,1.4fr);gap:28px;margin-bottom:28px;padding:28px;border-radius:18px;background:#07151b;border:1px solid #155e75}.action-panel h3{margin:.35rem 0}.action-panel p{color:#94a3b8}.action-panel label,.login-card label{display:grid;gap:7px;font-size:.86rem;font-weight:700}.action-panel select,.action-panel textarea{padding:13px 15px;border:1px solid #0e7490;border-radius:9px;background:#071f29;color:#ecfeff;font:inherit}.action-panel textarea{resize:vertical}.two{display:grid;grid-template-columns:1fr 1fr;gap:12px}.action-panel button:disabled{opacity:.5}@media(max-width:760px){.action-panel,.two{grid-template-columns:1fr}}</style>
