<script setup>
import { computed, ref } from 'vue';
import { ApiError, api, session } from './api';
const username=ref(''),password=ref(''),user=ref(null),rows=ref([]),assignments=ref([]),assignmentId=ref(null),content=ref(''),attachmentUrl=ref(''),error=ref(''),notice=ref(''),busy=ref(false);const count=computed(()=>rows.value.length);const openAssignments=computed(()=>assignments.value.filter(x=>x.status!=='CLOSED'&&new Date(x.dueAt)>new Date()));
function logout(message=''){session.token='';user.value=null;rows.value=[];assignments.value=[];assignmentId.value=null;if(message)error.value=message}function fail(e){if(e instanceof ApiError&&e.status===401)return logout('会话已失效，请重新登录');error.value=e?.message||'操作失败，请重试'}
async function load(){try{[rows.value,assignments.value]=await Promise.all([api('/api/courses'),api('/api/assignments')]);if(!openAssignments.value.some(x=>x.id===assignmentId.value))assignmentId.value=openAssignments.value[0]?.id??null}catch(e){fail(e)}}
async function login(){if(!username.value.trim()||!password.value)return;busy.value=true;error.value='';try{const r=await api('/api/auth/login',{method:'POST',body:JSON.stringify({username:username.value.trim(),password:password.value})});session.token=r.token;user.value=r.user;password.value='';await load()}catch(e){fail(e)}finally{busy.value=false}}
async function submit(){if(!assignmentId.value||!content.value.trim())return;busy.value=true;error.value='';notice.value='';try{await api('/api/submissions',{method:'POST',body:JSON.stringify({assignmentId:assignmentId.value,content:content.value.trim(),attachmentUrl:attachmentUrl.value.trim()})});notice.value='作业已提交或更新。';content.value='';attachmentUrl.value=''}catch(e){fail(e)}finally{busy.value=false}}
</script>
<template><div class="app-shell"><div class="tabs"><b>课程桌面</b><span>待提交</span><span>已完成</span><span>成绩</span></div><main class="main"><header class="top"><div><p class="eyebrow">课程与作业提交工作台</p><h1>COURSE DESK</h1></div><div v-if="user" class="account"><span>{{user.displayName}} · {{user.role}}</span><button class="ghost" @click="logout()">退出</button></div></header>
<section v-if="!user" class="login-card"><div><small>SECURE ACCESS</small><h2>进入 COURSE DESK</h2><p>登录后查看课程与未截止作业，并提交真实内容。</p></div><form @submit.prevent="login"><label>用户名<input v-model.trim="username" autocomplete="username" maxlength="32" required></label><label>密码<input v-model="password" type="password" autocomplete="current-password" minlength="12" maxlength="128" required></label><button :disabled="busy">{{busy?'登录中…':'登录'}}</button></form></section>
<template v-else><section class="hero"><div><span class="kicker">课程</span><strong>{{count}}</strong><p>当前课程</p></div><div class="hero-copy"><h2>课程作业提交管理系统</h2><p>作业选择来自后端未截止任务，重复提交由后端按“作业 + 用户”更新同一记录。</p></div></section><section class="action-panel"><div><span class="kicker">SUBMISSION</span><h3>提交作业</h3><p>选择未截止任务，填写正文和可选附件链接。</p></div><form @submit.prevent="submit"><label>作业<select v-model.number="assignmentId" required><option disabled :value="null">请选择作业</option><option v-for="a in openAssignments" :key="a.id" :value="a.id">{{a.title}} · 截止 {{String(a.dueAt).replace('T',' ')}}</option></select></label><label>作业正文<textarea v-model.trim="content" maxlength="10000" rows="5" required placeholder="填写作业内容"></textarea></label><label>附件 URL<input v-model.trim="attachmentUrl" type="url" maxlength="2000" placeholder="https://…"></label><button :disabled="busy||!assignmentId">提交作业</button></form></section><p v-if="notice" class="notice" role="status">{{notice}}</p><p v-if="error" class="error" role="alert">{{error}}</p><section class="panel"><div class="panel-head"><h3>课程</h3><button class="ghost" :disabled="busy" @click="load">刷新</button></div><div class="cards"><article v-for="row in rows" :key="row.id" class="data-card"><span class="id">#{{row.id}}</span><h4>{{row.name||row.title||('课程 '+row.id)}}</h4><p>{{row.description||row.code||'暂无课程说明'}}</p><small>{{row.status||'ACTIVE'}}</small></article><div v-if="!rows.length" class="empty">暂无课程</div></div></section></template></main></div></template>
<style scoped>.action-panel{display:grid;grid-template-columns:minmax(220px,.65fr) minmax(320px,1.35fr);gap:28px;margin-bottom:28px;padding:28px;border-radius:18px;background:#fffdf5;border:1px solid #d6d3d1}.action-panel h3{margin:.35rem 0}.action-panel label,.login-card label{display:grid;gap:7px;font-size:.86rem;font-weight:700}.action-panel select,.action-panel textarea{padding:13px 15px;border:1px solid #a8a29e;border-radius:10px;background:#fff;font:inherit}.action-panel textarea{resize:vertical}.action-panel button:disabled{opacity:.5}@media(max-width:760px){.action-panel{grid-template-columns:1fr}}</style>
