<script setup>
import { computed, ref } from 'vue'; import { ApiError, api, session } from './api';
const username=ref(''),password=ref(''),user=ref(null),rows=ref([]),planId=ref(null),error=ref(''),notice=ref(''),busy=ref(false);const count=computed(()=>rows.value.length);const available=computed(()=>rows.value.filter(x=>x.enabled!==false&&x.status!=='DISABLED'));
function logout(m=''){session.token='';user.value=null;rows.value=[];planId.value=null;if(m)error.value=m}function fail(e){if(e instanceof ApiError&&e.status===401)return logout('会话已失效，请重新登录');error.value=e?.message||'操作失败，请重试'}
async function load(){try{rows.value=await api('/api/plans');if(!available.value.some(x=>x.id===planId.value))planId.value=available.value[0]?.id??null}catch(e){fail(e)}}
async function login(){if(!username.value.trim()||!password.value)return;busy.value=true;error.value='';try{const r=await api('/api/auth/login',{method:'POST',body:JSON.stringify({username:username.value.trim(),password:password.value})});session.token=r.token;user.value=r.user;password.value='';await load()}catch(e){fail(e)}finally{busy.value=false}}
async function purchase(){if(!planId.value)return;busy.value=true;error.value='';notice.value='';try{await api('/api/memberships',{method:'POST',body:JSON.stringify({planId:planId.value})});notice.value='会员套餐已开通。';await load()}catch(e){fail(e)}finally{busy.value=false}}
</script>
<template><div class="app-shell"><div class="metric-strip"><span>TRAIN</span><span>TRACK</span><span>RECOVER</span></div><main class="main"><header class="top"><div><p class="eyebrow">MEMBERSHIP / TRAINING CONTROL</p><h1>FORGE</h1></div><div v-if="user" class="account"><span>{{user.displayName}} · {{user.role}}</span><button class="ghost" @click="logout()">退出</button></div></header><section v-if="!user" class="login-card"><div><small>SECURE ACCESS</small><h2>进入 FORGE</h2><p>登录后查看当前套餐并以当前身份开通会员。</p></div><form @submit.prevent="login"><label>用户名<input v-model.trim="username" autocomplete="username" maxlength="32" required></label><label>密码<input v-model="password" type="password" autocomplete="current-password" minlength="12" maxlength="128" required></label><button :disabled="busy">{{busy?'登录中…':'登录'}}</button></form></section><template v-else><section class="hero"><div><span class="kicker">会员套餐</span><strong>{{count}}</strong><p>当前套餐</p></div><div class="hero-copy"><h2>健身房会员管理系统</h2><p>套餐选择来自实时服务端数据；购买动作不再依赖固定记录编号。</p></div></section><section class="action-panel"><div><span class="kicker">MEMBERSHIP</span><h3>开通套餐</h3><p>确认套餐名称、周期与价格后提交。</p></div><form @submit.prevent="purchase"><label>套餐<select v-model.number="planId" required><option disabled :value="null">请选择套餐</option><option v-for="p in available" :key="p.id" :value="p.id">{{p.name||('套餐 #'+p.id)}} · {{p.price!=null?'¥'+p.price:''}}</option></select></label><button :disabled="busy||!planId">确认开通</button></form></section><p v-if="notice" class="notice" role="status">{{notice}}</p><p v-if="error" class="error" role="alert">{{error}}</p><section class="panel"><div class="panel-head"><h3>会员套餐</h3><button class="ghost" :disabled="busy" @click="load">刷新</button></div><div class="cards"><article v-for="row in rows" :key="row.id" class="data-card"><span class="id">#{{row.id}}</span><h4>{{row.name||('套餐 '+row.id)}}</h4><p>{{row.description||row.durationDays?((row.durationDays||'')+' 天'):''}}</p><small>{{row.status||'AVAILABLE'}}</small></article><div v-if="!rows.length" class="empty">暂无套餐</div></div></section></template></main></div></template>
<style scoped>.action-panel{display:grid;grid-template-columns:minmax(220px,.65fr) minmax(300px,1.35fr);gap:28px;margin-bottom:28px;padding:28px;border-radius:20px;background:#0b1220;border:1px solid #334155}.action-panel h3{margin:.35rem 0}.action-panel p{color:#94a3b8}.action-panel label,.login-card label{display:grid;gap:7px;font-size:.86rem;font-weight:700}.action-panel select{padding:13px 15px;border:1px solid #475569;border-radius:10px;background:#111827;color:#f8fafc;font:inherit}.action-panel button:disabled{opacity:.5}@media(max-width:760px){.action-panel{grid-template-columns:1fr}}</style>
