<script setup>
import { computed, ref } from 'vue'; import { ApiError, api, session } from './api';
const username=ref(''),password=ref(''),user=ref(null),rows=ref([]),bookId=ref(null),error=ref(''),notice=ref(''),busy=ref(false);const count=computed(()=>rows.value.length);const available=computed(()=>rows.value.filter(x=>x.status==='AVAILABLE'&&x.availableCopies>0));
function logout(m=''){session.token='';user.value=null;rows.value=[];bookId.value=null;if(m)error.value=m}function fail(e){if(e instanceof ApiError&&e.status===401)return logout('会话已失效，请重新登录');error.value=e?.message||'操作失败，请重试'}
async function load(){try{rows.value=await api('/api/books');if(!available.value.some(x=>x.id===bookId.value))bookId.value=available.value[0]?.id??null}catch(e){fail(e)}}
async function login(){if(!username.value.trim()||!password.value)return;busy.value=true;error.value='';try{const r=await api('/api/auth/login',{method:'POST',body:JSON.stringify({username:username.value.trim(),password:password.value})});session.token=r.token;user.value=r.user;password.value='';await load()}catch(e){fail(e)}finally{busy.value=false}}
async function borrow(){if(!bookId.value)return;busy.value=true;error.value='';notice.value='';try{await api('/api/borrows',{method:'POST',body:JSON.stringify({bookId:bookId.value})});notice.value='借阅成功，请按期归还。';await load()}catch(e){fail(e)}finally{busy.value=false}}
</script>
<template><div class="app-shell"><div class="catalog-line">CATALOGUE NO. 08 · READING ROOM</div><main class="main"><header class="top"><div><p class="eyebrow">在线借阅与馆藏流转</p><h1>藏书室</h1></div><div v-if="user" class="account"><span>{{user.displayName}} · {{user.role}}</span><button class="ghost" @click="logout()">退出</button></div></header><section v-if="!user" class="login-card"><div><small>SECURE ACCESS</small><h2>进入藏书室</h2><p>登录后查看实时馆藏副本数量并发起借阅。</p></div><form @submit.prevent="login"><label>用户名<input v-model.trim="username" autocomplete="username" maxlength="32" required></label><label>密码<input v-model="password" type="password" autocomplete="current-password" minlength="12" maxlength="128" required></label><button :disabled="busy">{{busy?'登录中…':'登录'}}</button></form></section><template v-else><section class="hero"><div><span class="kicker">馆藏图书</span><strong>{{count}}</strong><p>当前馆藏</p></div><div class="hero-copy"><h2>线上图书借阅管理平台</h2><p>只允许选择状态可用且仍有副本的图书；并发副本扣减由服务端锁保护。</p></div></section><section class="action-panel"><div><span class="kicker">BORROW</span><h3>发起借阅</h3><p>选择可借图书，服务端将生成带到期时间的借阅记录。</p></div><form @submit.prevent="borrow"><label>图书<select v-model.number="bookId" required><option disabled :value="null">请选择图书</option><option v-for="b in available" :key="b.id" :value="b.id">{{b.title}} · {{b.author}} · 可借 {{b.availableCopies}}</option></select></label><button :disabled="busy||!bookId">确认借阅</button></form></section><p v-if="notice" class="notice" role="status">{{notice}}</p><p v-if="error" class="error" role="alert">{{error}}</p><section class="panel"><div class="panel-head"><h3>馆藏图书</h3><button class="ghost" :disabled="busy" @click="load">刷新</button></div><div class="cards"><article v-for="row in rows" :key="row.id" class="data-card"><span class="id">#{{row.id}}</span><h4>{{row.title||('图书 '+row.id)}}</h4><p>{{row.author||row.isbn||'作者信息待补充'}}</p><small>{{row.status}} · 可借 {{row.availableCopies}} / {{row.totalCopies}}</small></article><div v-if="!rows.length" class="empty">暂无馆藏</div></div></section></template></main></div></template>
<style scoped>.action-panel{display:grid;grid-template-columns:minmax(220px,.65fr) minmax(300px,1.35fr);gap:28px;margin-bottom:28px;padding:28px;border-radius:4px;background:#f7f1e3;border:1px solid #9f8461}.action-panel h3{margin:.35rem 0}.action-panel label,.login-card label{display:grid;gap:7px;font-size:.86rem;font-weight:700}.action-panel select{padding:13px 15px;border:1px solid #9f8461;background:#fffaf0;font:inherit}.action-panel button:disabled{opacity:.5}@media(max-width:760px){.action-panel{grid-template-columns:1fr}}</style>
