<script setup>
import { computed, ref } from 'vue'; import { ApiError, api, session } from './api';
const username=ref(''),password=ref(''),user=ref(null),rows=ref([]),postId=ref(null),proof=ref(''),error=ref(''),notice=ref(''),busy=ref(false);const count=computed(()=>rows.value.length);const claimable=computed(()=>rows.value.filter(x=>!['CLAIMED','CLOSED'].includes(x.status)));
function logout(m=''){session.token='';user.value=null;rows.value=[];postId.value=null;if(m)error.value=m}function fail(e){if(e instanceof ApiError&&e.status===401)return logout('会话已失效，请重新登录');error.value=e?.message||'操作失败，请重试'}
async function load(){try{rows.value=await api('/api/posts');if(!claimable.value.some(x=>x.id===postId.value))postId.value=claimable.value[0]?.id??null}catch(e){fail(e)}}
async function login(){if(!username.value.trim()||!password.value)return;busy.value=true;error.value='';try{const r=await api('/api/auth/login',{method:'POST',body:JSON.stringify({username:username.value.trim(),password:password.value})});session.token=r.token;user.value=r.user;password.value='';await load()}catch(e){fail(e)}finally{busy.value=false}}
async function claim(){if(!postId.value||!proof.value.trim())return;busy.value=true;error.value='';notice.value='';try{await api('/api/claims',{method:'POST',body:JSON.stringify({postId:postId.value,proof:proof.value.trim()})});notice.value='认领申请已提交，等待核验。';proof.value='';await load()}catch(e){fail(e)}finally{busy.value=false}}
</script>
<template><div class="app-shell"><div class="signal"><i></i><span>LOST</span><i></i><span>FOUND</span></div><main class="main"><header class="top"><div><p class="eyebrow">把失物带回正确的人身边</p><h1>拾光</h1></div><div v-if="user" class="account"><span>{{user.displayName}} · {{user.role}}</span><button class="ghost" @click="logout()">退出</button></div></header><section v-if="!user" class="login-card"><div><small>SECURE ACCESS</small><h2>进入拾光</h2><p>登录后可浏览失物信息并提交可核验的认领证明。</p></div><form @submit.prevent="login"><label>用户名<input v-model.trim="username" autocomplete="username" maxlength="32" required></label><label>密码<input v-model="password" type="password" autocomplete="current-password" minlength="12" maxlength="128" required></label><button :disabled="busy">{{busy?'登录中…':'登录'}}</button></form></section><template v-else><section class="hero"><div><span class="kicker">失物招领</span><strong>{{count}}</strong><p>当前信息</p></div><div class="hero-copy"><h2>校园失物招领平台</h2><p>认领目标来自实时帖子列表；证明材料由服务端关联到当前用户，不能伪造 owner。</p></div></section><section class="action-panel"><div><span class="kicker">CLAIM</span><h3>提交认领</h3><p>选择尚未关闭的信息并描述只有真实失主应知道的特征。</p></div><form @submit.prevent="claim"><label>物品<select v-model.number="postId" required><option disabled :value="null">请选择物品</option><option v-for="p in claimable" :key="p.id" :value="p.id">{{p.title||p.itemName||('记录 #'+p.id)}} · #{{p.id}}</option></select></label><label>核验说明<textarea v-model.trim="proof" maxlength="2000" rows="4" required placeholder="描述物品特征、丢失时间地点等核验信息"></textarea></label><button :disabled="busy||!postId">提交认领</button></form></section><p v-if="notice" class="notice" role="status">{{notice}}</p><p v-if="error" class="error" role="alert">{{error}}</p><section class="panel"><div class="panel-head"><h3>失物招领信息</h3><button class="ghost" :disabled="busy" @click="load">刷新</button></div><div class="cards"><article v-for="row in rows" :key="row.id" class="data-card"><span class="id">#{{row.id}}</span><h4>{{row.title||row.itemName||('记录 '+row.id)}}</h4><p>{{row.description||row.location||'暂无描述'}}</p><small>{{row.status||row.type}}</small></article><div v-if="!rows.length" class="empty">暂无信息</div></div></section></template></main></div></template>
<style scoped>.action-panel{display:grid;grid-template-columns:minmax(220px,.65fr) minmax(320px,1.35fr);gap:28px;margin-bottom:28px;padding:28px;border-radius:24px;background:#f8fff9;border:1px solid #bbf7d0}.action-panel h3{margin:.35rem 0}.action-panel label,.login-card label{display:grid;gap:7px;font-size:.86rem;font-weight:700}.action-panel select,.action-panel textarea{padding:13px 15px;border:1px solid #86efac;border-radius:12px;background:#fff;font:inherit}.action-panel textarea{resize:vertical}.action-panel button:disabled{opacity:.5}@media(max-width:760px){.action-panel{grid-template-columns:1fr}}</style>
