<script setup>
import { computed, ref } from 'vue'; import { ApiError, api, session } from './api';
const dateAfter=n=>{const d=new Date(Date.now()+n*86400000);return d.toISOString().slice(0,10)};
const username=ref(''),password=ref(''),user=ref(null),rows=ref([]),productId=ref(null),quantity=ref(1),recipientName=ref(''),recipientPhone=ref(''),deliveryAddress=ref(''),deliveryDate=ref(dateAfter(1)),message=ref(''),error=ref(''),notice=ref(''),busy=ref(false);const count=computed(()=>rows.value.length);const onSale=computed(()=>rows.value.filter(x=>x.status==='ON_SALE'&&x.stock>0));
function logout(m=''){session.token='';user.value=null;rows.value=[];productId.value=null;if(m)error.value=m}function fail(e){if(e instanceof ApiError&&e.status===401)return logout('会话已失效，请重新登录');error.value=e?.message||'操作失败，请重试'}
async function load(){try{rows.value=await api('/api/products');if(!onSale.value.some(x=>x.id===productId.value))productId.value=onSale.value[0]?.id??null}catch(e){fail(e)}}
async function login(){if(!username.value.trim()||!password.value)return;busy.value=true;error.value='';try{const r=await api('/api/auth/login',{method:'POST',body:JSON.stringify({username:username.value.trim(),password:password.value})});session.token=r.token;user.value=r.user;password.value='';await load()}catch(e){fail(e)}finally{busy.value=false}}
async function order(){if(!productId.value||!recipientName.value.trim()||!recipientPhone.value.trim()||!deliveryAddress.value.trim())return;busy.value=true;error.value='';notice.value='';try{await api('/api/orders',{method:'POST',body:JSON.stringify({productId:productId.value,quantity:Number(quantity.value),recipientName:recipientName.value.trim(),recipientPhone:recipientPhone.value.trim(),deliveryAddress:deliveryAddress.value.trim(),deliveryDate:deliveryDate.value,message:message.value.trim()})});notice.value='花礼订单已提交。';message.value='';await load()}catch(e){fail(e)}finally{busy.value=false}}
</script>
<template><div class="app-shell"><div class="ornament">✦ petal journal ✦</div><main class="main"><header class="top"><div><p class="eyebrow">花礼、心意与准时送达</p><h1>Petal & Stem</h1></div><div v-if="user" class="account"><span>{{user.displayName}} · {{user.role}}</span><button class="ghost" @click="logout()">退出</button></div></header><section v-if="!user" class="login-card"><div><small>SECURE ACCESS</small><h2>进入 Petal & Stem</h2><p>登录后选择在售花礼并填写真实配送信息。</p></div><form @submit.prevent="login"><label>用户名<input v-model.trim="username" autocomplete="username" maxlength="32" required></label><label>密码<input v-model="password" type="password" autocomplete="current-password" minlength="12" maxlength="128" required></label><button :disabled="busy">{{busy?'登录中…':'登录'}}</button></form></section><template v-else><section class="hero"><div><span class="kicker">花卉商品</span><strong>{{count}}</strong><p>当前商品</p></div><div class="hero-copy"><h2>花卉商品在线销售管理系统</h2><p>仅展示实时库存；库存扣减在服务端事务内完成，前端不预设商品 ID 或收件人。</p></div></section><section class="action-panel"><div><span class="kicker">DELIVERY</span><h3>创建花礼订单</h3><p>填写配送所需的最少信息，留言可选。</p></div><form @submit.prevent="order"><label>花礼<select v-model.number="productId" required><option disabled :value="null">请选择花礼</option><option v-for="p in onSale" :key="p.id" :value="p.id">{{p.name}} · ¥{{p.price}} · 库存 {{p.stock}}</option></select></label><div class="two"><label>数量<input v-model.number="quantity" type="number" min="1" max="100" required></label><label>配送日期<input v-model="deliveryDate" type="date" :min="dateAfter(0)" required></label></div><div class="two"><label>收件人<input v-model.trim="recipientName" maxlength="64" required autocomplete="name"></label><label>联系电话<input v-model.trim="recipientPhone" maxlength="32" required autocomplete="tel" inputmode="tel"></label></div><label>配送地址<input v-model.trim="deliveryAddress" maxlength="255" required autocomplete="street-address"></label><label>花卡留言<textarea v-model.trim="message" maxlength="1000" rows="3"></textarea></label><button :disabled="busy||!productId">提交订单</button></form></section><p v-if="notice" class="notice" role="status">{{notice}}</p><p v-if="error" class="error" role="alert">{{error}}</p><section class="panel"><div class="panel-head"><h3>花卉商品</h3><button class="ghost" :disabled="busy" @click="load">刷新</button></div><div class="cards"><article v-for="row in rows" :key="row.id" class="data-card"><span class="id">#{{row.id}}</span><h4>{{row.name}}</h4><p>{{row.description||row.category||'花礼'}}</p><small>{{row.status}} · ¥{{row.price}} · 库存 {{row.stock}}</small></article><div v-if="!rows.length" class="empty">暂无商品</div></div></section></template></main></div></template>
<style scoped>.action-panel{display:grid;grid-template-columns:minmax(220px,.6fr) minmax(340px,1.4fr);gap:28px;margin-bottom:28px;padding:28px;border-radius:28px;background:#fff8fb;border:1px solid #fbcfe8}.action-panel h3{margin:.35rem 0}.action-panel label,.login-card label{display:grid;gap:7px;font-size:.86rem;font-weight:700}.action-panel select,.action-panel textarea{padding:13px 15px;border:1px solid #f9a8d4;border-radius:14px;background:#fff;font:inherit}.action-panel textarea{resize:vertical}.two{display:grid;grid-template-columns:1fr 1fr;gap:12px}.action-panel button:disabled{opacity:.5}@media(max-width:760px){.action-panel,.two{grid-template-columns:1fr}}</style>
